[package]
name = "proximity-cli"
version = "0.1.1"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
description = "CLI to interact with ProximityDB"
license = "GPL-3.0"

[dependencies]
# Point dependencies
